export const INTEGRATION_SERVICES = [
  {
    connector: 'API',
    services: [
      {
        href: 'https://docs.open-metadata.org/v1.6.x-SNAPSHOT/connectors/api/rest',
        src: '/assets/services/openApi.png',
        alt: 'service-openai',
        name: 'OpenAPI',
      },
    ]
  },
  {
    connector: 'Database',
    services: [
      {
        href: 'https://docs.open-metadata.org/latest/connectors/database/adls-datalake',
        src: '/assets/services/adls.webp',
        alt: 'service-adls',
        name: 'ADLS Data Lake',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/athena',
        src: '/assets/services/athena.webp',
        alt: 'service-athena',
        name: 'Athena',
      },
      {
        href: 'https://docs.open-metadata.org/latest/connectors/database/s3-datalake',
        src: '/assets/services/amazons3.webp',
        alt: 'service-amazon-s3',
        name: 'AWS S3 Data Lake',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/azuresql',
        src: '/assets/services/azuresql.webp',
        alt: 'service-azuresql',
        name: 'Azure SQL',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/bigquery',
        src: '/assets/services/bigquery.webp',
        alt: 'service-bigquery',
        name: 'BigQuery',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/clickhouse',
        src: '/assets/services/clickhouse.webp',
        alt: 'service-clickhouse',
        name: 'ClickHouse',
      },
      {
        name: 'Couchbase',
        href: 'https://docs.open-metadata.org/connectors/database/couchbase',
        alt: 'service-couchbase',
        src: '/assets/services/couchbase.webp',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/deltalake',
        src: '/assets/services/deltalake.webp',
        alt: 'service-deltalake',
        name: 'Delta Lake',
      },
      {
        href: 'https://docs.open-metadata.org/v1.2.x/connectors/database/doris',
        src: '/assets/services/service-icon-doris.webp',
        alt: 'service-doris',
        name: 'Doris',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/druid',
        src: '/assets/services/druid.webp',
        alt: 'service-druid',
        name: 'Druid',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/databricks',
        src: '/assets/services/databrick.webp',
        alt: 'service-databrick',
        name: 'Databricks',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/domo-database',
        src: '/assets/services/service-icon-domo.webp',
        alt: 'service-domo',
        name: 'Domo',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/dynamodb',
        src: '/assets/services/dynamodb.webp',
        alt: 'service-dynamodb',
        name: 'DynamoDB',
      },
      {
        href: 'https://docs.open-metadata.org/latest/connectors/database/exasol',
        src: '/assets/services/exasol.png',
        alt: 'service-exasol',
        name: 'Exasol',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/glue',
        src: '/assets/services/glue.webp',
        alt: 'service-glue',
        name: 'Glue',
      },
      {
        href: 'https://docs.open-metadata.org/latest/connectors/database/gcs-datalake',
        src: '/assets/services/gcp.webp',
        alt: 'service-gcp',
        name: 'Google Cloud Service',
      },
      {
        href: 'https://docs.open-metadata.org/latest/connectors/database/gcs-datalake',
        src: '/assets/services/service-icon-gcs.png',
        alt: 'service-gcs',
        name: 'GCS Data Lake',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/greenplum',
        name: 'Greenplum',
        src: '/assets/services/greenplum.webp',
        alt: 'service-greenplum',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/hive',
        src: '/assets/services/hive.webp',
        alt: 'service-hive',
        name: 'Hive',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/db2',
        src: '/assets/services/ibmdb2.webp',
        alt: 'service-ibmdb2',
        name: 'IBM Db2',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/impala',
        src: '/assets/services/service-icon-impala.webp',
        alt: 'service-impala',
        name: 'Impala',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/mariadb',
        src: '/assets/services/mariadb.webp',
        alt: 'service-mariadb',
        name: 'MariaDB',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/mssql',
        src: '/assets/services/mssql.webp',
        alt: 'service-mssql',
        name: 'MSSQL',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/mysql',
        src: '/assets/services/mysql.webp',
        alt: 'service-mysql',
        name: 'MySQL',
      },
      {
        name: 'MongoDB',
        href: 'https://docs.open-metadata.org/connectors/database/mongodb',
        src: '/assets/services/mongodb.webp',
        alt: 'service-mongodb',
      },
      {
        name: 'SAP HANA',
        href: 'https://docs.open-metadata.org/connectors/database/sap-hana',
        src: '/assets/services/sap-hana.png',
        alt: 'service-sap-hana',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/oracle',
        src: '/assets/services/oracle.webp',
        alt: 'service-oracle',
        name: 'Oracle',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/postgres',
        src: '/assets/services/postgres.webp',
        alt: 'service-postgres',
        name: 'Postgres',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/presto',
        src: '/assets/services/presto.webp',
        alt: 'service-presto',
        name: 'Presto',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/redshift',
        src: '/assets/services/redshift.webp',
        alt: 'service-redshift',
        name: 'Redshift',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/salesforce',
        src: '/assets/services/salesforce.webp',
        alt: 'service-salesforce',
        name: 'Salesforce',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/sas',
        src: '/assets/services/sas-viya.svg',
        alt: 'service-sas-viya',
        name: 'SAS Viya',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/snowflake',
        src: '/assets/services/snowflake.webp',
        alt: 'service-snowflake',
        name: 'Snowflake',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/singlestore',
        src: '/assets/services/singlestore.webp',
        alt: 'service-singlestore',
        name: 'SingleStore',
      },
      {
        href: 'https://docs.open-metadata.org/latest/connectors/database/teradata',
        src: '/assets/services/teradata.svg',
        alt: 'service-teradata',
        name: 'Teradata',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/trino',
        src: '/assets/services/trino.webp',
        alt: 'service-trino',
        name: 'Trino',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/vertica',
        src: '/assets/services/vertica.webp',
        alt: 'service-vertica',
        name: 'Vertica',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/pinotdb ',
        src: '/assets/services/pinot.png',
        alt: 'service-pinot',
        name: 'Pinot DB',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/database/sqlite ',
        src: '/assets/services/sqllite.webp',
        alt: 'service-sqlite',
        name: 'SQL Lite',
      },
      {
        href: 'https://docs.open-metadata.org/latest/connectors/database/iceberg',
        src: '/assets/services/iceberg.webp',
        alt: 'service-iceberg',
        name: 'Iceberg',
      },
      {
        href: 'https://docs.open-metadata.org/latest/connectors/database/sap-erp',
        src: '/assets/services/sap-erp.webp',
        alt: 'service-sap-erp',
        name: 'SapErp',
      },
    ],
  },
  {
    connector: 'Messaging',
    services: [
      {
        href: 'https://docs.open-metadata.org/connectors/messaging/kafka',
        src: '/assets/services/kafka.webp',
        alt: 'service-kafka',
        name: 'Kafka',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/messaging/redpanda',
        src: '/assets/services/redpanda.webp',
        alt: 'service-redpanda',
        name: 'Redpanda',
      },
      {
        src: '/assets/services/service-icon-kinesis.webp',
        alt: 'service-icon-kinesis',
        name: 'Kinesis',
        href: 'https://docs.open-metadata.org/connectors/messaging/kinesis',
      },
    ],
  },
  {
    connector: 'Dashboard',
    services: [
      {
        href: 'https://docs.open-metadata.org/connectors/dashboard/looker',
        src: '/assets/services/looker.webp',
        alt: 'service-looker',
        name: 'Looker',
      },
      {
        name: 'Qlik Sense',
        href: 'https://docs.open-metadata.org/connectors/dashboard/qliksense',
        src: '/assets/services/qliksense.webp',
        alt: 'service-qliksense',
      },
      {
        name: 'Lightdash',
        href: 'https://docs.open-metadata.org/latest/connectors/dashboard',
        src: '/assets/services/lightdash.webp',
        alt: 'service-lightdash',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/dashboard/metabase',
        src: '/assets/services/metabase.webp',
        alt: 'service-metabase',
        name: 'Metabase',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/dashboard/mode',
        src: '/assets/services/mode.png',
        alt: 'service-mode',
        name: 'Mode',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/dashboard/powerbi',
        src: '/assets/services/powerbi.webp',
        alt: 'service-powerbi',
        name: 'Power BI',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/dashboard/redash',
        src: '/assets/services/redash.webp',
        alt: 'service-redash',
        name: 'Redash',
      },
      {
        href: 'https://docs.open-metadata.org/v1.6.x-SNAPSHOT/connectors/dashboard/sigma',
        src: '/assets/services/sigma.svg',
        alt: 'service-sigma',
        name: 'Sigma',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/dashboard/superset',
        src: '/assets/services/superset.webp',
        alt: 'service-superset',
        name: 'Superset',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/dashboard/tableau',
        src: '/assets/services/tableu.webp',
        alt: 'service-tablue',
        name: 'Tableau',
      },
      {
        src: '/assets/services/service-icon-quicksight.webp',
        alt: 'service-icon-quicksight',
        name: 'QuickSight',
        href: 'https://docs.open-metadata.org/connectors/dashboard/quicksight',
      },
    ],
  },
  {
    connector: 'Pipeline',
    services: [
      {
        href: 'https://docs.open-metadata.org/connectors/pipeline/airflow',
        src: '/assets/services/airflow.webp',
        alt: 'service-airflow',
        name: 'Airflow',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/pipeline/airbyte',
        src: '/assets/services/airbyte.webp',
        alt: 'service-airbyte',
        name: 'Airbyte',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/pipeline/dagster',
        src: '/assets/services/dagster.webp',
        alt: 'service-dagster',
        name: 'Dagster',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/pipeline/fivetran',
        src: '/assets/services/fivetran.webp',
        alt: 'service-Fivetran',
        name: 'Fivetran',
      },
      {
        src: '/assets/services/apachenifi.webp',
        alt: 'service-apachenifi',
        name: 'NiFi',
        href: 'https://docs.open-metadata.org/connectors/pipeline/nifi',
      },
      {
        name: 'Spline',
        href: 'https://docs.open-metadata.org/connectors/pipeline/spline',
        src: '/assets/services/spline.webp',
        alt: 'service-spline',
      },
      {
        name: 'Flink',
        href: 'https://docs.open-metadata.org/connectors/pipeline/flink',
        src: '/assets/services/service-icon-flink.png',
        alt: 'service-flink',
      },
      {
        name: 'DBT',
        href: 'https://docs.open-metadata.org/latest/connectors/pipeline/dbtcloud',
        src: '/assets/services/service-icon-dbt.png',
        alt: 'service-dbt',
      },
    ],
  },
  {
    connector: 'ML Model',
    services: [
      {
        href: 'https://docs.open-metadata.org/connectors/ml-model/mlflow',
        src: '/assets/services/mlflow.webp',
        alt: 'service-mlflow',
        name: 'MLflow',
      },
      {
        src: '/assets/services/service-icon-sagemaker.webp',
        alt: 'service-icon-sagemaker',
        name: 'SageMaker',
        href: 'https://docs.open-metadata.org/connectors/ml-model/sagemaker',
      },
    ],
  },
  {
    connector: 'Metadata',
    services: [
      {
        href: 'https://docs.open-metadata.org/connectors/metadata/amundsen',
        src: '/assets/services/amundsen.webp',
        alt: 'service-amundsen',
        name: 'Amundsen',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/metadata/atlas',
        src: '/assets/services/atlas.webp',
        alt: 'service-atlas',
        name: 'Atlas',
      },
      {
        href: 'https://docs.open-metadata.org/connectors/metadata/alationsink',
        src: '/assets/services/service-icon-alation-sink.png',
        alt: 'service-AlationSink',
        name: 'AlationSink',
      },
    ],
  },
  {
    connector: 'Search',
    services: [
      {
        name: 'Elasticsearch',
        href: 'https://docs.open-metadata.org/connectors/search/elasticsearch',
        src: '/assets/services/elasticsearch.webp',
        alt: 'service-elasticsearch',
      },
    ],
  },
  {
    connector: 'Storage',
    services: [
      {
        name: 'Google Cloud Storage',
        href: 'https://docs.open-metadata.org/connectors/storage/gcs',
        src: '/assets/services/service-icon-gcs.png',
        alt: 'service-gcs',
      },
      {
        name: 'AWS S3 Storage',
        href: 'https://docs.open-metadata.org/connectors/storage/s3',
        src: '/assets/services/amazons3.webp',
        alt: 'service-s3',
      },
    ],
  },
  {
    connector: 'Others',
    services: [
      {
        href: 'https://docs.open-metadata.org/latest',
        src: '/assets/services/ldap.webp',
        alt: 'service-ldap',
        name: 'LDAP',
      },
      {
        href: 'https://docs.open-metadata.org/latest',
        src: '/assets/services/sqlalchemy.webp',
        alt: 'service-sqlalchemy',
        name: 'SQLAlchemy',
      },
    ],
  },
];
