import { LearningCenterItem } from '../utils/filterUtils'

const IMAGE_PATH = '/assets/learning-center/banner'

export interface CategoryItem {
    header: string
    items?: string[]
}

export const LEARNING_CENTER_DATA: LearningCenterItem[] = [
    {
        id: 0,
        title: 'Getting Started with OpenMetadata',
        image: `${IMAGE_PATH}/getting-started.png`,
        slug: 'getting-started',
        cluster: 'Data Discovery & Data Catalog',
        resourceType: 'Tutorials',
    },
    {
        id: 1,
        title: 'Data Discovery - Traditional Methods, Challenges & How AI Can Help',
        image: `${IMAGE_PATH}/data-discovery.png`,
        slug: 'data-discovery',
        cluster: 'Data Discovery',
        resourceType: 'Articles',
    },
    {
        id: 2,
        title: 'Best Data Observability Software - Top 5 Solutions in 2025',
        image: `${IMAGE_PATH}/observability-software.png`,
        slug: 'data-observability-software',
        cluster: 'Data Observability',
        resourceType: 'Articles',
    },
    {
        id: 3,
        title: '5 Core Pillars of Data Observability and Evolution in the AI Age',
        image: `${IMAGE_PATH}/data-observability.png`,
        slug: 'data-observability',
        cluster: 'Data Observability',
        resourceType: 'Articles',
    },
    {
        id: 4,
        title: 'Connect Your MySQL Database to OpenMetadata: A Step-by-Step Guide',
        image: `${IMAGE_PATH}/mysql.png`,
        slug: 'mysql',
        cluster: 'Data Discovery',
        resourceType: 'Tutorials',
    },
    {
        id: 5,
        title: '7 Data Quality Dimensions - Which Ones are Right for Your Data?',
        image: `${IMAGE_PATH}/data-quality-dimensions.png`,
        slug: 'data-quality-dimensions',
        cluster: 'Data Quality',
        resourceType: 'Articles',
    },
    {
        id: 6,
        title: 'Data Quality Dimensions & Building Your Data Quality Framework [2025]',
        image: `${IMAGE_PATH}/data-quality.png`,
        slug: 'data-quality',
        cluster: 'Data Quality',
        resourceType: 'Articles',
    },
    {
        id: 7,
        title: 'Data Product: Types, Examples, and How to Build Your Own',
        image: `${IMAGE_PATH}/data-product.png`,
        slug: 'data-product',
        cluster: 'Data Mesh',
        resourceType: 'Articles',
    },
    {
        id: 8,
        title: 'Data Lineage Examples, Use Cases & Best Practices in 2025',
        image: `${IMAGE_PATH}/data-lineage-best-practices.png`,
        slug: 'data-lineage-examples',
        cluster: 'Data Lineage',
        resourceType: 'Articles',
    },
    {
        id: 9,
        title: 'Data Lineage Techniques, Use Cases, and Pro Tips',
        image: `${IMAGE_PATH}/data-lineage.png`,
        slug: 'data-lineage',
        cluster: 'Data Lineage',
        resourceType: 'Articles',
    },
    {
        id: 10,
        title: 'Data Catalog: How It Works, Key Challenges & How AI Can Help',
        image: `${IMAGE_PATH}/data-catalog.png`,
        slug: 'data-catalog',
        cluster: 'Data Catalog',
        resourceType: 'Articles',
    },
    {
        id: 11,
        title: 'Data Dictionary in 2025 - 5 Use Cases & 5 Critical Best Practices',
        image: `${IMAGE_PATH}/data-dictionary.png`,
        slug: 'data-dictionary',
        cluster: 'Data Catalog',
        resourceType: 'Articles',
    },
    {
        id: 12,
        title: 'Best Data Governance Platforms: Top 6 Solutions in 2025',
        image: `${IMAGE_PATH}/data-governance-platform.png`,
        slug: 'data-governance-platforms',
        cluster: 'Data Governance',
        resourceType: 'Articles',
    },
    {
        id: 13,
        title: 'Data Governance in 2025 - Challenges, Capabilities & Best Practices',
        image: `${IMAGE_PATH}/data-governance.png`,
        slug: 'data-governance',
        cluster: 'Data Governance',
        resourceType: 'Articles',
    },
    {
        id: 14,
        title: 'AI Governance - Components, Maturity Model, Frameworks, and Best Practices',
        image: `${IMAGE_PATH}/ai-governance.png`,
        slug: 'ai-governance',
        cluster: 'Data Governance',
        resourceType: 'Articles',
    },
    {
        id: 15,
        title: 'Data Steward - Responsibilities, Types & Tips for Success',
        image: `${IMAGE_PATH}/data-steward.png`,
        slug: 'data-steward',
        cluster: 'Data Governance',
        resourceType: 'Articles',
    },
    {
        id: 16,
        title: 'Data Quality Management in 2025 - Process, Challenges & Solutions',
        image: `${IMAGE_PATH}/data-quality-management.png`,
        slug: 'data-quality-management',
        cluster: 'Data Quality',
        resourceType: 'Articles',
    },
    {
        id: 17,
        title: 'Metadata in AI Systems: Use Cases, Examples & Best Practices',
        image: `${IMAGE_PATH}/metadata-in-ai.png`,
        slug: 'metadata-in-ai-systems',
        cluster: 'Metadata Management',
        resourceType: 'Articles',
    },
    {
        id: 18,
        title: 'Metadata Management in 2026: Processes, Use Cases, and Technologies',
        image: `${IMAGE_PATH}/metadata-management.png`,
        slug: 'metadata-management',
        cluster: 'Metadata Management',
        resourceType: 'Articles',
    },
    {
        id: 19,
        title: 'Data Culture Best Practices for Modern Data Teams',
        image: `${IMAGE_PATH}/data-culture-webinar.png`,
        link: '/resources/webinar/data-culture',
        cluster: 'Data Catalog',
        resourceType: 'Webinars And Whitepapers',
    },
    {
        id: 20,
        title: 'Data Management - Key Functions, Examples, Trends & Best Practices',
        image: `${IMAGE_PATH}/data-management.png`,
        slug: 'data-management',
        cluster: 'Data Management',
        resourceType: 'Articles',
    },
    {
        id: 21,
        title: 'Data Warehouses in 2026: Components, Use Cases, and Best Practices',
        image: `${IMAGE_PATH}/data-warehouse.png`,
        slug: 'data-warehouse',
        cluster: 'Data Warehouse',
        resourceType: 'Articles',
    },
    {
        id: 22,
        title: 'Data Integration in 2026: Architecture, Examples, and Best Practices',
        image: `${IMAGE_PATH}/data-integration.png`,
        slug: 'data-integration',
        cluster: 'Data Integration',
        resourceType: 'Articles',
    },
    {
        id: 23,
        title: 'GDPR Compliance - 10 Things You Need to Know [2026 Guide]',
        image: `${IMAGE_PATH}/gdpr-compliance.png`,
        slug: 'gdpr-compliance',
        cluster: 'Data Governance',
        resourceType: 'Articles',
    },
    {
        id: 24,
        title: 'Data Contracts: Key Components, Use Cases, and Examples',
        image: `${IMAGE_PATH}/data-contracts.png`,
        slug: 'data-contracts',
        cluster: 'Data Mesh',
        resourceType: 'Articles',
    },
    {
        id: 25,
        title: 'Data Mesh: Architecture, Capabilities, and Best Practices',
        image: `${IMAGE_PATH}/data-mesh.png`,
        slug: 'data-mesh',
        cluster: 'Data Mesh',
        resourceType: 'Articles',
    },
    {
        id: 26,
        title: 'Connecting OpenMetadata to Snowflake: A Step-by-Step Guide',
        image: `${IMAGE_PATH}/snowflake.png`,
        slug: 'snowflake',
        cluster: 'Data Discovery',
        resourceType: 'Tutorials',
    },
    {
        id: 27,
        title: "Connecting OpenMetadata to BigQuery: Unlocking Google's Data Ecosystem",
        image: `${IMAGE_PATH}/bigquery.png`,
        slug: 'bigquery',
        cluster: 'Data Discovery',
        resourceType: 'Tutorials',
    },
    {
        id: 28,
        title: 'Connecting Tableau to OpenMetadata: Unlocking Cross-Source Data Lineage',
        image: `${IMAGE_PATH}/tableau.png`,
        slug: 'tableau',
        cluster: 'Data Discovery',
        resourceType: 'Tutorials',
    },
    {
        id: 29,
        title: 'Connecting dbt to OpenMetadata: Enriching Your Data Lineage',
        image: `${IMAGE_PATH}/dbt.png`,
        slug: 'dbt',
        cluster: 'Data Discovery',
        resourceType: 'Tutorials',
    },
    {
        id: 30,
        title: 'Connecting Databricks to OpenMetadata: A Complete Guide',
        image: `${IMAGE_PATH}/databricks.png`,
        slug: 'databricks',
        cluster: 'Data Discovery',
        resourceType: 'Tutorials',
    },
    {
        id: 31,
        title: 'Data Quality Tools: Key Capabilities and Top 10 Options in 2026',
        image: `${IMAGE_PATH}/data-quality-tools.png`,
        slug: 'data-quality-tools',
        cluster: 'Data Quality',
        resourceType: 'Articles',
    },
    {
        id: 32,
        title: 'Data Lineage Tools: Key Features and 8 Solutions to Know in 2026',
        image: `${IMAGE_PATH}/data-lineage-tools.png`,
        slug: 'data-lineage-tools',
        cluster: 'Data Lineage',
        resourceType: 'Articles',
    },
    {
        id: 33,
        title: 'Data Governance Tools: Key Features and 8 Tools to Know in 2026',
        image: `${IMAGE_PATH}/governance-tools.png`,
        slug: 'data-governance-tools',
        cluster: 'Data Governance',
        resourceType: 'Articles',
    },
    {
        id: 34,
        title: 'Feature Deep Dive: Data Lineage How-Tos and Best Practices',
        image: `${IMAGE_PATH}/data-lineage-webinar.png`,
        link: '/resources/webinar/data-lineage',
        cluster: 'Data Lineage',
        resourceType: 'Webinars And Whitepapers',
    },
    {
        id: 35,
        title: 'AI-Powered Data Quality: Scaling Data Team Observability',
        image: `${IMAGE_PATH}/data-quality-webinar.png`,
        link: '/resources/webinar/data-quality',
        cluster: 'Data Quality',
        resourceType: 'Webinars And Whitepapers',
    },
    {
        id: 36,
        title: 'Building Scalable Data Governance with Automation and AI',
        image: `${IMAGE_PATH}/data-governance-webinar.png`,
        link: '/resources/webinar/data-governance',
        cluster: 'Data Governance',
        resourceType: 'Webinars And Whitepapers',
    },
]

export const CATEGORY_LIST: CategoryItem[] = [
    {
        header: 'All',
    },
    {
        header: 'Topics',
        items: [
            'Data Observability',
            'Data Governance',
            'Data Catalog',
            'Data Quality',
            'Data Lineage',
            'Data Discovery',
            'Data Mesh',
            'Data Integration',
            'Data Warehouse',
            'Data Management',
            'Metadata Management',
        ],
    },
    {
        header: 'Resource Types',
        items: ['Tutorials', 'Articles', 'Webinars And Whitepapers'],
    },
]
